# Generated by Django 5.1 on 2025-08-24 14:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('notes', models.TextField(blank=True, default=None, help_text='Notas del registro.', null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualización del registro.', verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Estado del registro.', verbose_name='activo')),
                ('is_deleted', models.BooleanField(default=False, help_text='Estado de eliminación del registro.', verbose_name='eliminado')),
                ('id_user_created', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario creador del registro 0 es anonimo.', null=True, verbose_name='usuario creador')),
                ('id_user_updated', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario actualizador del registro.', null=True, verbose_name='usuario actualizador')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('president', models.CharField(max_length=100, verbose_name='presidente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono')),
                ('vocal_a', models.CharField(max_length=100, verbose_name='Vocal A')),
                ('vocal_b', models.CharField(max_length=100, verbose_name='Vocal B')),
                ('aproved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='aprobado por')),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='revisado por')),
                ('date_review', models.DateField(blank=True, null=True, verbose_name='fecha de revisión')),
                ('date_approval', models.DateField(blank=True, null=True, verbose_name='fecha de aprobación')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
            },
        ),
        migrations.CreateModel(
            name='HistoricalClub',
            fields=[
                ('notes', models.TextField(blank=True, default=None, help_text='Notas del registro.', null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del registro.', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de ultima actualización del registro.', verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Estado del registro.', verbose_name='activo')),
                ('is_deleted', models.BooleanField(default=False, help_text='Estado de eliminación del registro.', verbose_name='eliminado')),
                ('id_user_created', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario creador del registro 0 es anonimo.', null=True, verbose_name='usuario creador')),
                ('id_user_updated', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario actualizador del registro.', null=True, verbose_name='usuario actualizador')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='nombre')),
                ('president', models.CharField(max_length=100, verbose_name='presidente')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono')),
                ('vocal_a', models.CharField(max_length=100, verbose_name='Vocal A')),
                ('vocal_b', models.CharField(max_length=100, verbose_name='Vocal B')),
                ('aproved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='aprobado por')),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='revisado por')),
                ('date_review', models.DateField(blank=True, null=True, verbose_name='fecha de revisión')),
                ('date_approval', models.DateField(blank=True, null=True, verbose_name='fecha de aprobación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Club',
                'verbose_name_plural': 'historical Clubs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
