# Generated by Django 5.1 on 2025-08-24 11:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLicense',
            fields=[
                ('notes', models.TextField(blank=True, default=None, help_text='Notas del registro.', null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del registro.', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de ultima actualización del registro.', verbose_name='fecha de actualización')),
                ('is_deleted', models.BooleanField(default=False, help_text='Estado de eliminación del registro.', verbose_name='eliminado')),
                ('id_user_created', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario creador del registro 0 es anonimo.', null=True, verbose_name='usuario creador')),
                ('id_user_updated', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario actualizador del registro.', null=True, verbose_name='usuario actualizador')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('license_key', models.CharField(db_index=True, max_length=250, verbose_name='clave de licencia')),
                ('activated_on', models.DateTimeField(blank=True, null=True, verbose_name='activada el')),
                ('expires_on', models.DateTimeField(blank=True, null=True, verbose_name='expira el')),
                ('enterprise', models.CharField(default='KOSMOFLOWERS', max_length=50, verbose_name='Empresa')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo?')),
                ('url_server', models.URLField(blank=True, null=True, verbose_name='URL del servidor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'historical Licencia',
                'verbose_name_plural': 'historical Licencias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('notes', models.TextField(blank=True, default=None, help_text='Notas del registro.', null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualización del registro.', verbose_name='fecha de actualización')),
                ('is_deleted', models.BooleanField(default=False, help_text='Estado de eliminación del registro.', verbose_name='eliminado')),
                ('id_user_created', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario creador del registro 0 es anonimo.', null=True, verbose_name='usuario creador')),
                ('id_user_updated', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario actualizador del registro.', null=True, verbose_name='usuario actualizador')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_key', models.CharField(max_length=250, unique=True, verbose_name='clave de licencia')),
                ('activated_on', models.DateTimeField(blank=True, null=True, verbose_name='activada el')),
                ('expires_on', models.DateTimeField(blank=True, null=True, verbose_name='expira el')),
                ('enterprise', models.CharField(default='KOSMOFLOWERS', max_length=50, verbose_name='Empresa')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo?')),
                ('url_server', models.URLField(blank=True, null=True, verbose_name='URL del servidor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenceActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default=None, help_text='Notas del registro.', null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualización del registro.', verbose_name='fecha de actualización')),
                ('is_deleted', models.BooleanField(default=False, help_text='Estado de eliminación del registro.', verbose_name='eliminado')),
                ('id_user_created', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario creador del registro 0 es anonimo.', null=True, verbose_name='usuario creador')),
                ('id_user_updated', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario actualizador del registro.', null=True, verbose_name='usuario actualizador')),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Información del dispositivo que activó la licencia', verbose_name='información del dispositivo')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se activó la licencia', null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador/aplicación', verbose_name='user agent')),
                ('is_active', models.BooleanField(default=True, help_text='Si esta activación está actualmente activa', verbose_name='activo')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Fecha de desactivación', null=True, verbose_name='desactivado en')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='accounts.license', verbose_name='licencia')),
            ],
            options={
                'verbose_name': 'Activación de Licencia',
                'verbose_name_plural': 'Activaciones de Licencias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLicenceActivation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default=None, help_text='Notas del registro.', null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del registro.', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de ultima actualización del registro.', verbose_name='fecha de actualización')),
                ('is_deleted', models.BooleanField(default=False, help_text='Estado de eliminación del registro.', verbose_name='eliminado')),
                ('id_user_created', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario creador del registro 0 es anonimo.', null=True, verbose_name='usuario creador')),
                ('id_user_updated', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario actualizador del registro.', null=True, verbose_name='usuario actualizador')),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Información del dispositivo que activó la licencia', verbose_name='información del dispositivo')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se activó la licencia', null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador/aplicación', verbose_name='user agent')),
                ('is_active', models.BooleanField(default=True, help_text='Si esta activación está actualmente activa', verbose_name='activo')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Fecha de desactivación', null=True, verbose_name='desactivado en')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.license', verbose_name='licencia')),
            ],
            options={
                'verbose_name': 'historical Activación de Licencia',
                'verbose_name_plural': 'historical Activaciones de Licencias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
