# Generated by Django 5.1 on 2025-11-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('CLUB_MANAGER', 'CLUB_MANAGER'), ('PLAYER', 'PLAYER')], default='CLUB_MANAGER', help_text='Perfil o rol del usuario en el sistema.', max_length=20, verbose_name='perfil'),
        ),
    ]
