# Generated by Django 5.1 on 2025-08-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_historicallicense_license_licenceactivation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenceactivation',
            name='license',
        ),
        migrations.DeleteModel(
            name='HistoricalLicenceActivation',
        ),
        migrations.DeleteModel(
            name='LicenceActivation',
        ),
    ]
