# Generated by Django 5.1 on 2025-08-24 14:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
        ('seasons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegister',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default=None, help_text='Notas del registro.', null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del registro.', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de ultima actualización del registro.', verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Estado del registro.', verbose_name='activo')),
                ('is_deleted', models.BooleanField(default=False, help_text='Estado de eliminación del registro.', verbose_name='eliminado')),
                ('id_user_created', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario creador del registro 0 es anonimo.', null=True, verbose_name='usuario creador')),
                ('id_user_updated', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario actualizador del registro.', null=True, verbose_name='usuario actualizador')),
                ('category', models.CharField(choices=[('NIÑOS', 'NIÑOS'), ('FEMENINO', 'FEMENINO'), ('SENIOR', 'SENIOR'), ('MASTER', 'MASTER')], max_length=10, verbose_name='categoría')),
                ('number', models.PositiveIntegerField(verbose_name='número jugador')),
                ('minor_authorization', models.TextField(blank=True, max_length=100, null=True, verbose_name='autorización menor')),
                ('photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='foto fondo claro')),
                ('id_document', models.TextField(blank=True, max_length=100, null=True, verbose_name='foto cédula')),
                ('is_requalification', models.BooleanField(default=False, verbose_name='recalificación')),
                ('status', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=10, verbose_name='estado')),
                ('have_pass', models.BooleanField(default=False, verbose_name='tiene pase')),
                ('before_club', models.CharField(blank=True, max_length=100, null=True, verbose_name='club Anterior')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('club', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clubs.club')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='players.player')),
                ('season', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='seasons.season')),
            ],
            options={
                'verbose_name': 'historical Registro aspirante',
                'verbose_name_plural': 'historical Registros aspirantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default=None, help_text='Notas del registro.', null=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro.', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualización del registro.', verbose_name='fecha de actualización')),
                ('is_active', models.BooleanField(default=True, help_text='Estado del registro.', verbose_name='activo')),
                ('is_deleted', models.BooleanField(default=False, help_text='Estado de eliminación del registro.', verbose_name='eliminado')),
                ('id_user_created', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario creador del registro 0 es anonimo.', null=True, verbose_name='usuario creador')),
                ('id_user_updated', models.PositiveIntegerField(blank=True, default=0, help_text='Identificador del usuario actualizador del registro.', null=True, verbose_name='usuario actualizador')),
                ('category', models.CharField(choices=[('NIÑOS', 'NIÑOS'), ('FEMENINO', 'FEMENINO'), ('SENIOR', 'SENIOR'), ('MASTER', 'MASTER')], max_length=10, verbose_name='categoría')),
                ('number', models.PositiveIntegerField(verbose_name='número jugador')),
                ('minor_authorization', models.FileField(blank=True, null=True, upload_to='autorizaciones/', verbose_name='autorización menor')),
                ('photo', models.FileField(blank=True, null=True, upload_to='fotos_registro/', verbose_name='foto fondo claro')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='cedulas/', verbose_name='foto cédula')),
                ('is_requalification', models.BooleanField(default=False, verbose_name='recalificación')),
                ('status', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=10, verbose_name='estado')),
                ('have_pass', models.BooleanField(default=False, verbose_name='tiene pase')),
                ('before_club', models.CharField(blank=True, max_length=100, null=True, verbose_name='club Anterior')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registers', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registers', to='seasons.season')),
            ],
            options={
                'verbose_name': 'Registro aspirante',
                'verbose_name_plural': 'Registros aspirantes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['season', 'club', 'category'], name='register_re_season__756eb8_idx'), models.Index(fields=['player'], name='register_re_player__7fcf6f_idx')],
                'unique_together': {('season', 'club', 'category', 'player')},
            },
        ),
    ]
